version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - $HOME/DDK/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: ${DB_PASSWORD}
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - "80:80"
    links:
      - wordpress:php-fpm-server
    depends_on:
      - wordpress
    volumes:
      - $HOME/DDK/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
      - /tmp/bindfs/${DIR}:/var/www/html:ro
  wordpress:
    image: kumaxim/xdebug-wordpress:php7.2-fpm
    restart: on-failure
    links:
      - db:mysql
    depends_on:
      - db
    expose:
      - "9000"
      - "9900"
    volumes:
      - /tmp/bindfs/${DIR}:/var/www/html
      - $HOME/DDK/docker-php-core-settings.ini:/usr/local/etc/php/conf.d/docker-php-core-settings.ini:ro
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WP_DEBUG: 1
      XDEBUG_REMOTE_ENABLE: 1
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_PORT: 9900
      XDEBUG_IDEKEY: phpstorm
      XDEBUG_REMOTE_HOST: "172.18.0.1"

networks:
  default:
    external:
      name: local-bridge
